apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbit-proxy
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/media/qbit-proxy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

