apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: unpackerr
    namespace: media
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: unpackerr
            version: 15.6.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      global:
        stopAll: false
      credentials:
        s3v3:
          type: s3
          url: "${S3_MINIO_URL_V2}"
          bucket: "${S3_MINIO_BUCKET_PREFIX}-v2-{{ .Chart.Name }}"
          accessKey: "${S3_MINIO_KEY_ID_V2}"
          secretKey: "${S3_MINIO_SECRET_KEY_V2}"
          encrKey: "${S3_MINIO_SECRET_KEY_V2}"
      persistence:
        config:
          volsync:
            - name: config
              type: restic
              credentials: s3v3
              dest:
                enabled: true
              src:
                enabled: true
        downloads:
          volsync:
            - name: downloads
              type: restic
              credentials: s3v3
              dest:
                enabled: true
              src:
                enabled: true
        plex-media:
          enabled: true
          existingClaim: plex-media-pvc
          mountPath: /mnt
      workload:
        main:
          podSpec:
            containers:
              main:
                advanced: false
                envList:
                - name: UN_RADARR_0_URL
                  value: http://radarr.media.svc.cluster.local:7878
                - name: UN_RADARR_0_API_KEY
                  value: ${RADARR_KEY}
                - name: UN_SONARR_0_URL
                  value: http://sonarr.media.svc.cluster.local:8989
                - name: UN_SONARR_0_API_KEY
                  value: ${SONARR_KEY}
      portal:
        open:
          enabled: false