---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: excalidraw
  namespace: utilities
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3v3:
        type: s3
        url: "${S3_MINIO_URL_V2}"
        bucket: "${S3_MINIO_BUCKET_PREFIX}-{{ .Chart.Name }}"
        accessKey: "${S3_MINIO_KEY_ID_V2}"
        secretKey: "${S3_MINIO_SECRET_KEY_V2}"
        encrKey: "${S3_MINIO_SECRET_KEY_V2}"
    image:
      repository: excalidraw/excalidraw
      pullPolicy: IfNotPresent
      tag: latest
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        allowPrivilegeEscalation: true
        privileged: true
        UMASK: "002"
        runAsUser: 0
        runAsGroup: 0
        PUID: 0
    #     # capabilities:
    #       # add:
    #         # - NET_ADMIN
    #     # pod:
    #     #   sysctls:
    #     #     - name: net.ipv4.conf.all.src_valid_mark
    #     #       value: "1"
    service:
      main:
        ports:
          main:
            port: 10094
      # proxy:
      #   enabled: true
      #   ports:
      #     proxy:
      #       enabled: true
      #       port: 8118
      #       protocol: "http"
      #       targetPort: 8118
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: excalidraw.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - excalidraw.${DOMAIN_0}
            clusterIssuer: domain-0-le-prod
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod

    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        targetSelectAll: true
        volsync:
          - name: config
            type: restic
            credentials: s3v3
            dest:
              enabled: true
            src:
              enabled: true
