# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: threadfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: threadfin
      version: 1.1.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3v3:
        type: s3
        url: "${S3_MINIO_URL_V2}"
        bucket: "${S3_MINIO_BUCKET_PREFIX}-v2-{{ .Chart.Name }}"
        accessKey: "${S3_MINIO_KEY_ID_V2}"
        secretKey: "${S3_MINIO_SECRET_KEY_V2}"
        encrKey: "${S3_MINIO_SECRET_KEY_V2}"
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3v2
            dest:
              enabled: true
            src:
              enabled: true
      temp:
        volsync:
          - name: temp
            type: restic
            credentials: s3v2
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 50 6 * * *
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: threadfin.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - threadfin.${DOMAIN_0}
            clusterIssuer: domain-0-le-prod
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod