apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: it-tools
    namespace: utilities
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: it-tools
            version: 8.0.6
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      # ingress:
      #   main:
      #     enabled: true
      #     integrations:
      #       traefik:
      #         enabled: true
      #         entrypoints:
      #         - websecure
      #       certManager:
      #         enabled: true
      #         certificateIssuer: domain-0-le-prod
      #     hosts:
      #       - host: it.${DOMAIN_0}
      #         paths:
      #           - path: /
      #             pathType: Prefix
      ingress:
        main:
          enabled: true
          ingressClassName: internal
          hosts:
            - host: it.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - it.${DOMAIN_0}
              clusterIssuer: domain-0-le-prod
          integrations:
            traefik:
              enabled: false
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod