apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 23.8.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    portal:
      open:
        enabled: false
    global:
      stopAll: false
    credentials:
      s3v3:
        type: s3
        url: "${S3_MINIO_URL_V2}"
        bucket: "${S3_MINIO_BUCKET_PREFIX}-{{ .Chart.Name }}"
        accessKey: "${S3_MINIO_KEY_ID_V2}"
        secretKey: "${S3_MINIO_SECRET_KEY_V2}"
        encrKey: "${S3_MINIO_SECRET_KEY_V2}"
    # ingress:
    #   main:
    #     enabled: true
    #     tls:
    #       - hosts:
    #           - sonarr2.${DOMAIN_0}
    #         clusterIssuer: domain-0-wildcard
    #     hosts:
    #       - host: sonarr2.${DOMAIN_0}
    #         paths:
    #           - path: /
    #             pathType: Prefix
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: sonarr2.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - sonarr2.${DOMAIN_0}
            clusterIssuer: domain-0-le-prod
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod

    # ingress:
    #   main:
    #     enabled: true
    #     ingressClassName: internal
    #     hosts:
    #       - host: sonarr2.${DOMAIN_0}
    #     integrations:
    #       traefik:
    #         enabled: false
    #       certManager:
    #         enabled: true
    #         certificateIssuer: cloudflare



  
    # ingress:
    #   main:
    #     enabled: true
    #     ingressClassName: "internal"
    #     annotations:
    #       nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #     tls:
    #       - hosts:
    #           - sonarr2.${DOMAIN_0}
    #         clusterIssuer: domain-0-le-prod
    #     hosts:
    #       - host: sonarr2.${DOMAIN_0}
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #     integrations:
    #       traefik:
    #         enabled: false
    #       # homepage:
    #       #   enabled: true
    #       #   name: Sonarr (Series)
    #       #   group: "Media Manager"
    #       #   siteMonitor: http://sonarr.sonarr.svc.cluster.local:8989
    #       #   widget:
    #       #     custom:
    #       #       key: "${SONARR_SERIES_KEY}"
    #       # certManager:
    #       #   enabled: true
    #       #   certificateIssuer: general-le-prod
    #       certManager:
    #         enabled: true
    #         certificateIssuer: domain-0-le-prod
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: s3v3
          dest:
            enabled: true
          src:
            enabled: true
            trigger:
              schedule: 50 0 * * *
      plex-media:
        enabled: true
        existingClaim: plex-media-pvc
        mountPath: /mnt
    metrics:
      main:
        enabled: false